### PR TITLE
Framework

### PR DESCRIPTION
**Pull request by ricardovaltierra**
Waiting for first code review.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi team!  
#### Your project looks :+1:  and very discriptive readme file!
#### But need some Required Changes

### [OPTIONAL]

### Responsiveness

#### Breakpoints


- [x] The CSS files should define a breakpoint for small screens with a width of up to 720px

- [x] The CSS files should define a breakpoint for medium screens with a width in the range of 720px - 1024px

- [x] The CSS files should define a breakpoint for large screens with width above 1024px

### Box utilities

#### Margins

* [x] The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
* [x] The margins should span from `0 rem` to `1 rem`
* [x] The margins should have breakpoints (e.g. margin-sm-top-1)

#### Padding

* [x] The CSS files define separate classes for padding top, bottom, left, right, all padding and auto
* [x] The padding should span from `0 rem` to `1 rem`
* [x] The padding should have breakpoints (example padding-lg-2)

### Positioning

#### Floats

* [x] The CSS files define separate classes for float left, right and clearing the floats

#### Positions

* [x] The CSS files define separate classes to change the position property of an element to relative, absolute or fixed

### Display

#### Display properties

The CSS files define:

* [x] A class to set the display property of an element to flex
* [x] A class to set the display property to hidden
* [x] A class to set the display property to none
* [x] The none class should have breakpoints (example display-md-none)

#### Flex properties

The CSS files define:

* [x] Classes to set vertical alignment as top, bottom or center
* [x] Classes to set horizontal alignment as left, right or center

### Colors

#### Background and text

The CSS files define:

* [x] At least ten different classes to set the background and text colors of an element

### Text

#### Utilities

The CSS files define:

* [x] Classes to horizontally align text to the left, right or center
* [x] At least five classes to set the font size of an element
* [x] Three classes to set the font weight of an element (bold, normal, medium)

#### Border

* [x] The CSS files define separate classes for border top, bottom, left, right, all border
* [x] The border should span from 0 to 1rem
* [x] The border should have classes for making box round
* [x] The border should have a class defined to transform a box into a circle


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes.

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes Required 🛑 
### Hello @ricardovaltierra @FelipeEnne, 👋 You done a very good job cloning the odin's project website but still you have fix below requirements,
- [x]  ignore .sass-cache folder 📂, which not useful for this project
- [x]  Classes to define columns sized from 1/12th of the row to 100% of the row
- [x]  A class that represents a row
- [x]  The defined columns should have breakpoints (example column-large-2)([Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59564673/))

----
### Don't forget to request for another code review 
----
**Happy Coding** 
Pon Muthu Selvam N
**If you have any doubts, Feel free to contact me on slack**
[Github // @imhta](https://github.com/imhta)
[Twitter // @ponmuthuselvam](https://twitter.com/ponmuthuselvam)

**Review by ebukaume — CHANGES_REQUESTED** [review]
## Changes Required

Hi team,

You guys are doing really well. It is nice that you implemented most of the requested changes. Please let's get `.sass-cache` directory properly excluded from this repo. You can refer to this [SOF](https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore) for help.

**Kindly submit another code review request after making the requested change**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by suretrust** [comment]
Hi team,

### Amazing job implementing the suggested changes. Looks good to me. :+1: 

Don't forget to close [this issue](https://github.com/ricardovaltierra/design-your-own-grid-based-framework/issues/2).

_Good luck with your future projects and happy coding!_

**Review by suretrust — APPROVED** [review]
Hi team,

### Amazing job implementing the suggested changes. Looks good to me. :+1: 

Don't forget to close [this issue](https://github.com/ricardovaltierra/design-your-own-grid-based-framework/issues/2).

_Good luck with your future projects and happy coding!_

**Pull request merged**
